system: "base16"
name: "blueberry_new"
author: "guy, SmArtKar"
variant: "dark"
palette:
  base00: "#14131d"
  base01: "#282342"
  base02: "#343051"
  base03: "#565384"
  base04: "#8181bb"
  base05: "#cacaff"
  base06: "#ddddff"
  base07: "#eee9Fd"
  base08: "#ff7c7c" 
  base09: "#ff9d7c"
  base0A: "#fff87c"
  base0B: "#7cff7c"
  base0C: "#7cdeff"
  base0D: "#92a6e5"
  base0E: "#a687e5"
  base0F: "#de92e5"
