system: "base16"
name: "Needles"
author: "SmArtKar"
variant: "dark"
palette:
  base00: "#09040F"
  base01: "#110a19"
  base02: "#1a1426"
  base03: "#28223A"
  base04: "#ABA9C6"
  base05: "#DADBED"
  base06: "#EFF4FC"
  base07: "#FCFDFE"
  base08: "#EA647D"
  base09: "#EA8A52"
  base0A: "#EAC952"
  base0B: "#87CE5F"
  base0C: "#75C9EA"
  base0D: "#668DE2"
  base0E: "#A483E2"
  base0F: "#D483E2"
