system: "base16"
name: "Needles"
author: "SmArtKar"
variant: "dark"
palette:
  base00: "#09040F"
  base01: "#121019"
  base02: "#161426"
  base03: "#22243A"
  base04: "#ADB1C6"
  base05: "#DADEED"
  base06: "#EFF4FC"
  base07: "#FCFDFE"
  base08: "#F7768E"
  base09: "#FF9E64"
  base0A: "#FFDD63"
  base0B: "#9ECE6A"
  base0C: "#89DDFF"
  base0D: "#7AA2F7"
  base0E: "#BB9AF7"
  base0F: "#E999F7"
